name: smart-crossover

channels:
  - conda-forge
  - gurobi

dependencies:
  - python=3.7.16
  - pandas=1.3.5
  - scipy=1.7.3
  - gurobi=9.0.3
  - matplotlib=3.4.3
  - numpy=1.21.3

  - pip:
      - cplex=12.9.0
      - mosek=9.3.14
      - -e .